[package]
name = "openjev-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "openjev"
path = "src/main.rs"

[features]
default = []
native = ["openjev-llama/native"]
metal = ["native", "openjev-llama/metal"]
cuda = ["native", "openjev-llama/cuda"]
integration = ["native", "openjev-llama/integration"]

[dependencies]
anyhow.workspace = true
clap.workspace = true
openjev-core = { path = "../openjev-core" }
openjev-llama = { path = "../openjev-llama", default-features = false }
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
